

logging:
  level:
    io.github.cooperlyt: INFO

mis:
  jackson:
    zoned-date:
      enable: true
      local-time-zone: Asia/Shanghai

spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

server:
  port: 8081

person:
  people:
    card:
      validExpire: true

rocks:
  path: /tmp/rocksdb
  enabled: false
  dbs:
    fs:
      filename: fs-db